POST http://localhost/api/analysis_credit/
Content-Type: application/json

{
  "education": "higher",
  "sex": "M",
  "age": 32,
  "car": "yes",
  "car_type": "foreign",
  "decline_app_cnt": 0,
  "good_work": 1,
  "score_bki": 790,
  "bki_request_cnt": 1,
  "region_rating": 1,
  "home_address": 1,
  "work_address": 1,
  "income": 150000,
  "sna": 1,
  "first_time": 0,
  "foreign_passport": "no",
  "app_date": "01FEB2014"
}
