POST http://localhost/api/analysis_insurance/
Content-Type: application/json

{
  "months_as_customer": 84,
  "age": 45,
  "policy_deductable": 1000,
  "policy_annual_premium": 1100,
  "umbrella_limit": 0,

  "incident_hour_of_the_day": 11,
  "number_of_vehicles_involved": 1,
  "bodily_injuries": 0,
  "witnesses": 2,

  "injury_claim": 0,
  "property_claim": 1200,
  "vehicle_claim": 4500,

  "policy_state": "CA",
  "insured_sex": "MALE",
  "insured_education_level": "Masters",
  "incident_type": "Single Vehicle Collision",
  "collision_type": "Rear Collision",
  "incident_severity": "Minor Damage",
  "authorities_contacted": "Police",
  "property_damage": "YES",
  "police_report_available": "YES",
  "auto_make": "Toyota"
}
